import { ts, pause, notif, text, emote, pic, choice, call } from "../helpers";

export const version = "test-1.0"

export const chars = [{
    key: "test-char",
    name: "Test Texts",
    pfp: "/pfp/flins.gif",
    chatpfp: "/pfp/flins.png",
    chats: [
        ts("12:00"),
        notif("A sample notification!"),
        text("This is a test text!"),
        text("This is a test text with 5 seconds timeout", null, 5000),
        emote("/emote/jahoda11.png"),
        pic("/pfp/varka.webp"),
        choice(null, null, 
            "text", "option1", "Option 1",
            "text", "option2", "Option 2"),
        text("This should show up when you select Option 1.", "option1"),
        text("This should show up when you select Option 2.", "option2"),
        choice("option2", null, 
            "text", "option2-1", "Option 2's Option 1",
            "text", "option2-2", "Option 2's Option 2"),
        text("This should show up when you select Option 2 then Option 1.", "option2-1"),
        text("This should show up when you select Option 2 then Option 2.", "option2-2"),
        text("This should show up regardless you selected Option 1 or Option 2."),
        text("There will be a 5 second pause after this message."),
        pause(5000),
    ]
}, {
    key: "test-call",
    name: "Test Call",
    pfp: "/pfp/zhongli.gif",
    chatpfp: "/pfp/zhongli.jpg",
    chats: [
        notif("Call started 21:20"),
        call("This is a test call."),
        call("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur iaculis turpis vel lorem faucibus commodo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. "),
        call("Donec ut porttitor quam. Phasellus vestibulum diam mi, consectetur viverra metus gravida vel."),
        call("Sed sed felis eget nunc convallis efficitur. Donec a semper enim, id efficitur ligula. Donec in sem ac odio varius efficitur."),
        call("Duis posuere dui quam, ut suscipit ante venenatis eget. Donec tempus mi mi, sed egestas diam rutrum non. Donec ultrices velit id sem pulvinar, nec efficitur turpis convallis."),
        call("Nullam ac nunc sed enim efficitur efficitur. Donec eget ligula a metus efficitur efficitur. Donec ut nisi a enim efficitur efficitur."),
        call("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur iaculis turpis vel lorem faucibus commodo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. "),
        call("Donec ut porttitor quam. Phasellus vestibulum diam mi, consectetur viverra metus gravida vel."),
        call("Sed sed felis eget nunc convallis efficitur. Donec a semper enim, id efficitur ligula. Donec in sem ac odio varius efficitur."),
        call("Duis posuere dui quam, ut suscipit ante venenatis eget. Donec tempus mi mi, sed egestas diam rutrum non. Donec ultrices velit id sem pulvinar, nec efficitur turpis convallis."),
        call("Nullam ac nunc sed enim efficitur efficitur. Donec eget ligula a metus efficitur efficitur. Donec ut nisi a enim efficitur efficitur."),
        call("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur iaculis turpis vel lorem faucibus commodo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. "),
        call("Donec ut porttitor quam. Phasellus vestibulum diam mi, consectetur viverra metus gravida vel."),
        call("Sed sed felis eget nunc convallis efficitur. Donec a semper enim, id efficitur ligula. Donec in sem ac odio varius efficitur."),
        call("Duis posuere dui quam, ut suscipit ante venenatis eget. Donec tempus mi mi, sed egestas diam rutrum non. Donec ultrices velit id sem pulvinar, nec efficitur turpis convallis."),
        call("Nullam ac nunc sed enim efficitur efficitur. Donec eget ligula a metus efficitur efficitur. Donec ut nisi a enim efficitur efficitur."),
        call("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur iaculis turpis vel lorem faucibus commodo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. "),
        call("Donec ut porttitor quam. Phasellus vestibulum diam mi, consectetur viverra metus gravida vel."),
        call("Sed sed felis eget nunc convallis efficitur. Donec a semper enim, id efficitur ligula. Donec in sem ac odio varius efficitur."),
        call("Duis posuere dui quam, ut suscipit ante venenatis eget. Donec tempus mi mi, sed egestas diam rutrum non. Donec ultrices velit id sem pulvinar, nec efficitur turpis convallis."),
        call("Nullam ac nunc sed enim efficitur efficitur. Donec eget ligula a metus efficitur efficitur. Donec ut nisi a enim efficitur efficitur."),
        call("Call will end in 5 seconds."),
        pause(5000),
        notif("Call ended 3h 1m"),
    ]
}].sort((a, b) => a.key.localeCompare(b.key));
